import event1 from "@/assets/event1.jpg";
import event2 from "@/assets/event2.jpg";
import event3 from "@/assets/event3.jpg";
import event4 from "@/assets/event4.jpg";
import event5 from "@/assets/event5.jpg";
import eventOpera from "@/assets/event-opera.jpg";
import eventClassical from "@/assets/event-classical.jpg";
import eventPop from "@/assets/event-pop.jpg";

export interface Event {
  id: string;
  title: string;
  category: string;
  date: string;
  time: string;
  venue: string;
  city: string;
  price: number;
  image: string;
  description: string;
  availableSeats: number;
  totalSeats: number;
}

export interface Ticket {
  id: string;
  event: Event;
  seat: string;
  section: string;
  quantity: number;
  totalPrice: number;
  purchaseDate: string;
  status: "active" | "used" | "expired";
  qrCode: string;
}

export const categories = [
  { id: "all", label: "Todos", icon: "🎪" },
  { id: "concerts", label: "Conciertos", icon: "🎵" },
  { id: "theater", label: "Teatro", icon: "🎭" },
  { id: "opera", label: "Ópera", icon: "🎼" },
  { id: "comedy", label: "Comedia", icon: "😂" },
  { id: "festivals", label: "Festivales", icon: "🎉" },
  { id: "sports", label: "Deportes", icon: "⚽" },
];

export const events: Event[] = [
  {
    id: "1",
    title: "Bad Bunny — Most Wanted Tour",
    category: "concerts",
    date: "2026-07-12",
    time: "20:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    price: 120,
    image: event1,
    description: "El conejo malo regresa con su gira mundial más esperada. Un show explosivo con sus mayores éxitos del reggaetón y trap latino.",
    availableSeats: 2500,
    totalSeats: 87000,
  },
  {
    id: "2",
    title: "Karol G — Mañana Será Bonito World Tour",
    category: "concerts",
    date: "2026-07-25",
    time: "21:00",
    venue: "Estadio Nacional",
    city: "Lima",
    price: 95,
    image: event1,
    description: "La Bichota presenta su gira mundial con sus mayores hits: Provenza, TQG, Mientras Me Curo del Cora y muchos más.",
    availableSeats: 4000,
    totalSeats: 50000,
  },
  {
    id: "3",
    title: "Taylor Swift — The Eras Tour 2026",
    category: "concerts",
    date: "2026-08-03",
    time: "20:00",
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    price: 250,
    image: eventPop,
    description: "Un viaje a través de todas las eras musicales de Taylor: Fearless, Red, 1989, Reputation, Lover, Folklore, Evermore y Midnights. Más de 3 horas de show.",
    availableSeats: 1500,
    totalSeats: 87000,
  },
  {
    id: "4",
    title: "Coldplay — Music of the Spheres",
    category: "concerts",
    date: "2026-08-14",
    time: "20:30",
    venue: "Estadio River Plate",
    city: "Buenos Aires",
    price: 140,
    image: eventPop,
    description: "Chris Martin y la banda regresan con su gira más visual y emotiva, llena de pulseras LED, fuegos artificiales y los grandes himnos como 'Fix You' y 'Yellow'.",
    availableSeats: 12000,
    totalSeats: 84000,
  },
  {
    id: "5",
    title: "Tomorrowland Brasil 2026",
    category: "festivals",
    date: "2026-08-22",
    time: "16:00",
    venue: "Parque Maeda",
    city: "São Paulo",
    price: 220,
    image: event4,
    description: "El festival de música electrónica más mágico del mundo llega a Latinoamérica con DJs como Martin Garrix, David Guetta y Armin van Buuren.",
    availableSeats: 8000,
    totalSeats: 60000,
  },
  {
    id: "6",
    title: "Final Copa Libertadores 2026",
    category: "sports",
    date: "2026-09-05",
    time: "18:00",
    venue: "Estadio Monumental",
    city: "Santiago",
    price: 180,
    image: event5,
    description: "La gran final del torneo más importante del fútbol sudamericano. Una noche histórica.",
    availableSeats: 5000,
    totalSeats: 70000,
  },
  {
    id: "7",
    title: "Romeo y Julieta — Compañía Nacional",
    category: "theater",
    date: "2026-07-18",
    time: "19:30",
    venue: "Teatro Colón",
    city: "Bogotá",
    price: 45,
    image: event2,
    description: "La obra clásica de Shakespeare en una producción moderna y espectacular dirigida por la Compañía Nacional de Teatro.",
    availableSeats: 150,
    totalSeats: 1200,
  },
  {
    id: "8",
    title: "El Fantasma de la Ópera",
    category: "theater",
    date: "2026-09-12",
    time: "20:30",
    venue: "Teatro Gran Rex",
    city: "Buenos Aires",
    price: 75,
    image: eventOpera,
    description: "El musical de Andrew Lloyd Webber regresa con producción de West End. Una historia de amor, obsesión y tragedia bajo la Ópera de París.",
    availableSeats: 600,
    totalSeats: 3300,
  },
  {
    id: "9",
    title: "Hamilton — Tour Latinoamérica",
    category: "theater",
    date: "2026-10-04",
    time: "20:00",
    venue: "Teatro Municipal",
    city: "Santiago",
    price: 130,
    image: event2,
    description: "El musical revolucionario de Lin-Manuel Miranda finalmente en español. Hip-hop, historia y emoción en cada acto.",
    availableSeats: 800,
    totalSeats: 2400,
  },
  {
    id: "10",
    title: "Carmen — Bizet",
    category: "opera",
    date: "2026-07-30",
    time: "20:00",
    venue: "Palacio de Bellas Artes",
    city: "Ciudad de México",
    price: 95,
    image: eventOpera,
    description: "La célebre ópera de Georges Bizet con la pasión gitana de Sevilla. Habanera y Toreador en vivo.",
    availableSeats: 280,
    totalSeats: 1800,
  },
  {
    id: "11",
    title: "La Traviata — Verdi",
    category: "opera",
    date: "2026-08-28",
    time: "19:30",
    venue: "Teatro Colón",
    city: "Buenos Aires",
    price: 110,
    image: eventOpera,
    description: "La inmortal ópera de Giuseppe Verdi sobre Violetta y Alfredo, interpretada por la orquesta estable y solistas internacionales.",
    availableSeats: 350,
    totalSeats: 2500,
  },
  {
    id: "12",
    title: "Andrea Bocelli en Concierto",
    category: "opera",
    date: "2026-10-20",
    time: "21:00",
    venue: "Movistar Arena",
    city: "Bogotá",
    price: 180,
    image: eventClassical,
    description: "El tenor italiano interpreta clásicos como 'Con Te Partirò', 'Time to Say Goodbye' y arias de las grandes óperas.",
    availableSeats: 1200,
    totalSeats: 14000,
  },
  {
    id: "13",
    title: "Franco Escamilla — Sin Filtro",
    category: "comedy",
    date: "2026-07-22",
    time: "21:00",
    venue: "Movistar Arena",
    city: "Buenos Aires",
    price: 55,
    image: event3,
    description: "Una noche cargada de humor sin censura con uno de los comediantes más populares de habla hispana.",
    availableSeats: 800,
    totalSeats: 12000,
  },
  {
    id: "14",
    title: "Stand-Up Bogotá Comedy Fest",
    category: "comedy",
    date: "2026-09-19",
    time: "21:30",
    venue: "Teatro Coliseo",
    city: "Bogotá",
    price: 35,
    image: event3,
    description: "Los mejores stand-uperos colombianos: Alejandro Riaño, Iván Marín y sorpresas especiales.",
    availableSeats: 400,
    totalSeats: 1600,
  },
  {
    id: "15",
    title: "Lollapalooza Argentina 2026",
    category: "festivals",
    date: "2026-11-13",
    time: "12:00",
    venue: "Hipódromo de San Isidro",
    city: "Buenos Aires",
    price: 165,
    image: event4,
    description: "Tres días con los mejores artistas internacionales: Dua Lipa, The Weeknd, Olivia Rodrigo, Tame Impala y más de 100 bandas.",
    availableSeats: 15000,
    totalSeats: 100000,
  },
  {
    id: "16",
    title: "Cosquín Rock 2026",
    category: "festivals",
    date: "2026-10-10",
    time: "14:00",
    venue: "Aeródromo Santa María",
    city: "Córdoba",
    price: 85,
    image: event4,
    description: "El festival de rock más importante de Argentina. Dos días con más de 80 bandas en 4 escenarios simultáneos.",
    availableSeats: 9000,
    totalSeats: 45000,
  },
  {
    id: "17",
    title: "Luis Miguel — Tour Sinfónico",
    category: "concerts",
    date: "2026-11-02",
    time: "21:00",
    venue: "Movistar Arena",
    city: "Santiago",
    price: 110,
    image: event1,
    description: "El Sol de México regresa con sus boleros, baladas y rancheras acompañado de orquesta sinfónica completa.",
    availableSeats: 3000,
    totalSeats: 16000,
  },
  {
    id: "18",
    title: "Sinfónica Beethoven — 9ª Sinfonía",
    category: "concerts",
    date: "2026-09-26",
    time: "20:00",
    venue: "Auditorio Nacional",
    city: "Ciudad de México",
    price: 65,
    image: eventClassical,
    description: "La Orquesta Sinfónica Nacional interpreta la majestuosa Novena Sinfonía con coro completo y el inolvidable 'Himno a la Alegría'.",
    availableSeats: 900,
    totalSeats: 9700,
  },
  {
    id: "19",
    title: "Clásico River vs Boca",
    category: "sports",
    date: "2026-10-25",
    time: "17:00",
    venue: "Estadio Monumental",
    city: "Buenos Aires",
    price: 95,
    image: event5,
    description: "El superclásico del fútbol argentino. Un partido que paraliza al país entero.",
    availableSeats: 3500,
    totalSeats: 84000,
  },
  {
    id: "20",
    title: "NBA Global Games México",
    category: "sports",
    date: "2026-12-05",
    time: "20:30",
    venue: "Arena Ciudad de México",
    city: "Ciudad de México",
    price: 220,
    image: event5,
    description: "Lakers vs Warriors en suelo mexicano. Una noche única de baloncesto NBA en Latinoamérica.",
    availableSeats: 2000,
    totalSeats: 22000,
  },
  {
    id: "21",
    title: "Don Giovanni — Mozart",
    category: "opera",
    date: "2026-11-18",
    time: "19:30",
    venue: "Teatro Municipal",
    city: "Santiago",
    price: 85,
    image: eventOpera,
    description: "La obra maestra de Mozart sobre el legendario seductor. Producción con dirección escénica contemporánea.",
    availableSeats: 200,
    totalSeats: 900,
  },
  {
    id: "22",
    title: "Bizarrap & Friends en vivo",
    category: "concerts",
    date: "2026-08-08",
    time: "22:00",
    venue: "Movistar Arena",
    city: "Buenos Aires",
    price: 75,
    image: eventPop,
    description: "Bizarrap presenta sus sessions más virales con invitados sorpresa en una noche irrepetible.",
    availableSeats: 2200,
    totalSeats: 14000,
  },
];

export const sampleTickets: Ticket[] = [
  {
    id: "t1",
    event: events[0],
    seat: "A-15",
    section: "VIP",
    quantity: 2,
    totalPrice: 240,
    purchaseDate: "2026-04-10",
    status: "active",
    qrCode: "GLOW-2026-001-A15",
  },
  {
    id: "t2",
    event: events[2],
    seat: "F-8",
    section: "General",
    quantity: 1,
    totalPrice: 55,
    purchaseDate: "2026-04-12",
    status: "active",
    qrCode: "GLOW-2026-003-F8",
  },
];
